### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by jgebal** [usrecnik/ddlfs#12]
Hi @usrecnik 
This looks very promising.
Is there any chance that ddlfs would work on Windows (with cygwin or any other Unix emulator?)

If not, what would be your suggestion to use it on Windows? Virtoualbox/docker with Ubuntu & mapped drive?

**Comment by usrecnik** [comment]
Maybe :)

Cygwin should be fairly easy to try altough I have my doubts because libfuse is relying on FUSE kernel module..

Quick Google search also found https://dokan-dev.github.io/ which looks promising.. 
I'll do some more digging and hopefully come up with Windows support. I just need to clear my backlog at work first :(

**Comment by jgebal** [comment]
Doing it for Windows would be awesome from development perspective.

Thanks a mil.
That is really powerful and innovative piece of software!

**Comment by usrecnik** [comment]
I started working on this (see new "windows" branch at  a29f7c840d725c6ace47ef2ae16634fb0a2d8944).

Currently, it compiles and it lists database objects on Windows using Dokan. 
It compiles natively using MSVC and thus produces native .exe binary (no cygwin or docker required).

This is kind of prof-of-concept code currently, it's neither complete nor pretty (hence a separate branch).

So.. it seems that there's a good chance that Windows port will be released in 2019 :)

**Comment by jgebal** [comment]
That is really great.
I saw @pioro presenting on it today at UKOUG 2018.
He showed a great use-case for it.

**Comment by jgebal** [comment]
@usrecnik 
I'm surprised that the work of yours was not picked up and didn't cause a major disturbance.
It is really a breakthrough. Did you share this within Oracle community?

**Comment by usrecnik** [comment]
Yep, I thought the same and was a bit surprised when not much interest was shown. I did present at SIOUG conference and posted a few twits on Twitter where some of the big names from Oracle subscribed. But nothing much happened after.

Is there another/better way to share this project with Oracle community?

Maybe it's time to try to revive this - it's about time to create a new release to at least include latest OCI drivers. Maybe also build this Windows build as a "beta".

**Comment by pioro** [comment]
Having a windows version will be great.
Actually I would like to discuss with you some changes which I think could be very useful and probably allows better adoption as well. I was trying to implement something myself but my OCI voodoo is pretty low and my FUSE voodoo is almost not existing so I used a different approach to extract metadata using Python.  I maybe open a new issue with description later this week.

**Comment by jgebal** [comment]
I've just mentioned this tool to 2 more Oracle ACEs, so hoping to get more traction.
I'm planning to play a bit with the Linux version to get more familiar and comfortable with it.

**Comment by usrecnik** [comment]
Windows version (beta!) finally released:

https://github.com/usrecnik/ddlfs/releases/tag/3.0-RC1

I've also updated README.md to describe how to build it on Windows.

**Comment by jgebal** [comment]
Amazing! 
👏
I will try it out.
Thank you.
